"""
Django settings for Whatsapp_reminder project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d=d!d^svjf^l0uok0b21iqh8mfjf(*mdjzm-95t(_cms%i+i_n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'AutoMensaje',
    'django_celery_beat',
    'django_celery_results',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    'coreapi',
    'corsheaders',
    'django_extensions',
]

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
    # Comentado para eliminar autenticación y permisos:
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
         'rest_framework.permissions.IsAuthenticated',
    ),
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Esta línea puede ser eliminada si no necesitas autenticación
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:3001',  
]


ROOT_URLCONF = 'Whatsapp_reminder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Whatsapp_reminder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Usamos PostgreSQL
        'NAME': 'whatsapp_db',  # El nombre de tu base de datos en PostgreSQL
        'USER': 'postgresUser',  # Usuario de PostgreSQL (por defecto suele ser 'postgres')
        'PASSWORD': 'MAUD2023.',  # La contraseña de tu usuario 'postgres'
        'HOST': 'localhost',  # O la dirección IP de tu servidor de base de datos (si es remoto)
        'PORT': '5432',  # El puerto por defecto de PostgreSQL
    }
}

AUTH_USER_MODEL = 'AutoMensaje.User'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Managua'

USE_I18N = True

USE_TZ = True


# Celery configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_TIMEZONE = 'America/Managua'
CELERY_REDIS_SOCKET_TIMEOUT = 10  # Aumenta el tiempo de espera si es necesario


# Celery configuration for retries and timeout handling
CELERY_REDIS_MAX_CONNECTIONS = 5  # Limita el número de conexiones simultáneas
CELERY_REDIS_SOCKET_KEEPALIVE = True  # Habilita el "keepalive" de socket para evitar desconexiones

# Retry options
CELERY_ACKS_LATE = True  # Confirma las tareas solo cuando hayan sido completadas, no cuando se reciban
CELERY_TASK_RETRY = True  # Reintenta tareas en caso de fallo
CELERY_TASK_RETRY_POLICY = {
    'max_retries': 5,  # Maximo de reintentos
    'interval_start': 0,  # Intervalo inicial entre intentos (en segundos)
    'interval_step': 0.2,  # Tiempo de espera entre reintentos
    'interval_max': 1,  # Tiempo máximo de espera entre reintentos
}



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
