# Generated by Django 4.2.17 on 2025-01-25 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoMensaje', '0003_remove_cliente_user_sucursal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AutoMensaje.sucursal'),
        ),
    ]
