# Generated by Django 4.2.17 on 2025-02-01 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoMensaje', '0004_alter_cliente_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AutoMensaje.sucursal'),
        ),
    ]
