# Generated by Django 4.2.17 on 2025-03-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoMensaje', '0005_alter_cliente_placa_alter_cliente_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='placa',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
